### ISSUE TITLE
Remove external node configuration to example file

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/scenario-player#360]
## Problem

Within the current example file it is written:

```yaml
nodes:
  ## Mode, either `managed` or `external`
  # - managed: The scenario player will manage the Raiden nodes
  # - external: The nodes need to be managed externally (see v1 for examples)
  mode: managed
```
The v1 example file is not avaible anymore in 
https://github.com/raiden-network/scenario-player/tree/master/examples

The commit which deleted it was
https://github.com/raiden-network/scenario-player/commit/d9390849f46abbe57173106a04a555e776432546#diff-b7e6ad2834c284e1323007cada49bddf

## Solution

Remove in [the current example file](https://github.com/raiden-network/scenario-player/blob/master/examples/scenario-example-v2.yaml) the instructions how to manage an external node.
