### ISSUE TITLE
Make scenario specific setting overwritable: Default options

### ISSUE THREAD

**Issue by czepluch** [raiden-network/scenario-player#446]
Analysis
=======
Introduction
-----------------
Currently each scenario has some hardcoded settings specified. Some of these settings should be made overwritable through the CLI arguments of the scenario player when starting a scenario in order to make scenarios more dynamic in regards to which environment they are run in. This should be done as a solution to https://github.com/raiden-network/team/issues/682. 

At the moment all default options of a Raiden node can also be specified as an option in the scenarios. It would be helpful to be able to specify these when starting up the scenario player, so that it's easy to adjust the scenarios to run in different environments. @nlsdfnbch mentioned that he already have some templating stuff ready to help with this.

Solution
----------
Make it possible to overwrite the
```
token:
  default_options:
    environment-type: development
    routing-mode: pfs
    enable-monitoring: true
    proportional-fee:
      - "0x62083c80353Df771426D209eF578619EE68D5C7A"
    proportional-imbalance-fee:
      - "0x62083c80353Df771426D209eF578619EE68D5C7A"
```
setting through an argument when starting the Scenario Player.
