### ISSUE TITLE
AssertPFSIOU task keeps retrying until 5min timeout even if it's succeeding

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/scenario-player#611]
Description
=========
It eventually succeeds, but takes 5min timeout, even though the request condition is fulfilled in the first request.
I didn't notice this behavior on other tasks, only on `AssertPFSIOU`

Task:
```
AssertPFSIOU 0:04:04.681630: {'source': 3, 'amount': 500000000000000000}
```

Logs filled with:
```
{"url": "https://pfs.transport01.raiden.network/api/v1/_debug/ious/0xA0661172D1aD4eDf76fDF3fAd2bE5F49ac9f4425", "method": "get", "json": {}, "event": "Requesting", "logger": "scenario_player.tasks.api_base", "level": "debug", "greenlet_name": "orchestration", "timestamp": "2020-10-08 13:45:40.442408"}
{"json": {"sender": "0xA0661172D1aD4eDf76fDF3fAd2bE5F49ac9f4425", "amount": 500000000000000000, "expiration_block": 3739450}, "event": "Received response", "logger": "scenario_player.tasks.api_base", "level": "debug", "greenlet_name": "orchestration", "timestamp": "2020-10-08 13:45:40.607931"}
{"ex": "None", "event": "Assertion failed, retrying...", "logger": "scenario_player.tasks.base", "level": "debug", "greenlet_name": "orchestration", "timestamp": "2020-10-08 13:45:40.609282"}
```

Return of that `_debug` URL request:
```json
{
    "amount": 500000000000000000,
    "expiration_block": 3739450,
    "sender": "0xA0661172D1aD4eDf76fDF3fAd2bE5F49ac9f4425"
}
```

Expected Behavior
===============
The task succeeds the first time the URL returns the expected value.

**Comment by agatsoh** [comment]
Same is the case with assert_events task
```
## Wait for channel to be closed
      - wait_blocks: 10
      - assert: {from: 0, to: 1, total_deposit: 1_000_000_000_000_000_000, balance: 500_000_000_000_000_000, state: "closed"}
      - assert_events:
          contract_name: "TokenNetwork"
          event_name: "ChannelClosed"
          num_events: 1
          event_args: {closing_participant: 0}
```
```
{"task": "<AssertBlockchainEventsTask: {'contract_name': 'TokenNetwork', 'event_name': 'ChannelClosed', 'num_events': 1, 'event_args': {'closing_participant': 0}}>", "id": "10", "event": "Starting task", "logger": "scenario_player.tasks.base", "level": "info", "greenlet_name": "orchestration", "timestamp": "2020-10-08 09:43:16.430773"}
{"timeout": 300, "event": "Running task with timeout", "logger": "scenario_player.tasks.base", "level": "debug", "greenlet_name": "orchestration", "timestamp": "2020-10-08 09:43:16.433063"}
{"ex": "None", "event": "Assertion failed, retrying...", "logger": "scenario_player.tasks.base", "level": "debug", "greenlet_name": "orchestration", "timestamp": "2020-10-08 09:43:16.837555"}
.
.
.
{"ex": "None", "event": "Timeout reached", "logger": "scenario_player.tasks.base", "level": "debug", "greenlet_name": "orchestration", "timestamp": "2020-10-08 09:48:16.450198"}
{"id": "10", "task": "<AssertBlockchainEventsTask: {'contract_name': 'TokenNetwork', 'event_name': 'ChannelClosed', 'num_events': 1, 'event_args': {'closing_participant': 0}}>", "runtime": 300.0182739220036, "event": "Task successful", "logger": "scenario_player.tasks.base", "level": "info", "greenlet_name": "orchestration", "timestamp": "2020-10-08 09:48:16.451324"}

```
